#!/bin/bash
mkdir vin
cd vin
touch v1 v2 v3 v4
mkdir /opt/viki
cd ..
cd vin
cp v2 v3 /opt/viki
apt install openjdk-11-jre-headless -y
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
tar -xvf apache-tomcat-9.0.76.tar.gz
mv apache-tomcat-9.0.76 tomcat
cd tomcat/bin
sh startup.sh
cd /
cp 'index.html?ddownload=14486' /vin/tomcat/webapps
cp *.war /vin/tomcat/webapps
# here am creating one directory
mkdir ajaiy
cd ajaiy
touch vinod1 vinod2 vinod3.txt
cp *.txt /opt/viki
useradd vinod -p vinod
a=$((10+3))
b=$((10*3))
echo $((a-b))

echo "what do u want print"
read aa
echo $aa

read -p "this is "  name
echo " your name is "$name

*** shotcut**
if we want to go first line of vi editor then  press ESC button then type "gg"
and also you want delete all content line what ever having existing file  press "ESC" then type "dG" it will be all deleted


****varible concept*****

#!/bin/bash
read -p 'enter any number ' a
read -p 'enter second number ' b
echo "your addition is $((a+b))"
echo "your sybtaction is $((a-b))"
echo "your multiplication is $((a*b))"

***** array concept**

here we can stored in values afer finally we can get what ever we want output

systax s as show in below 

array name is vinod
index is [] = its like a option we want to print output by using index value


vinod=[[1]=100 [2]=200 [3]=300) or vinod=(100 200 300 400)

suppose i need all values as stored in array i can write like this 
echo ${vinod[*]} or echo ${vinod[*]}

i want start with 3 index 

echo ${vinod[*]:3}
echo ${vinod[@]:2:4}

i need values of as my reqirement 

echo $(vinod[@]:3:7}










